<?php
/**
 * Serves a cached OG image by hash. Routed from /og/<hash>.png.
 *
 * Files are pre-generated by Seo::generateOgImage when a page renders
 * its meta tags, so this handler is just a static-file lookup with a
 * fixed cache dir + path-traversal guard.
 */
$hash = (string)($params['hash'] ?? '');
if (!preg_match('/^[0-9a-f]{32}$/', $hash)) {
    http_response_code(400); exit('bad hash');
}
$path = __DIR__ . '/../data/cache/og/' . $hash . '.png';
if (!is_file($path)) {
    http_response_code(404); exit('not found');
}
header('Content-Type: image/png');
header('Cache-Control: public, max-age=31536000, immutable');
header('Content-Length: ' . filesize($path));
readfile($path);
